
//should return all categories(only the names)
GET http://localhost:5000/categories

###

//should return all subcategories
GET http://localhost:5000/categories/genre

###

// should return invalid category
GET http://localhost:5000/categories/decade

###