
// Get all vinyls
GET http://localhost:5000/products

###

// Get a specific vinyl based on id 
GET http://localhost:5000/products/4


###

// Get vinyls by category -> genre -> 'rock'
GET http://localhost:5000/products?genre=Rock

###

// Get vinyls by category -> artist -> 'Metallica'
GET http://localhost:5000/products?artist=Metallica

###


// Get vinyls by category -> decades -> '70s'
GET http://localhost:5000/products?decade=70s

###

// Get vinyls by using two categories -> genre + decades
GET http://localhost:5000/products?genre=Rock&decade=70s

###

// Get vinyls by using three categories -> genre + decades + artist
GET http://localhost:5000/products?genre=Rock&decade=70s&artist=Led Zeppelin

###

// Empty response:
GET http://localhost:5000/products?genre=Rock&decade=2010s&artist=The Beatles